### ISSUE TITLE
XML3D doesn't load properly with require.js

### ISSUE THREAD

**Issue by Arsakes** [xml3d/xml3d.js#140]
As In title, require.js provides a way to load non-AMD (Asynchronous module definition) modules, so it should work with XML3D, despite this it doesn't. 
http://stackoverflow.com/questions/32018311/loading-xml3d-with-require-js

**Comment by csvurt** [comment]
You're right, this was a simple oversight when initializing XML3D. I've pushed a fix to  our upcoming 4.9.4 hotfix that should be released later this week. 

Thanks for the bug report!

**Comment by Arsakes** [comment]
Works as a charm. Closing.

**Comment by Arsakes** [comment]
Just a comment: This solution works however it seems that one needs to have <xml3d></xml3d> tag present in document BEFORE xml3d library is actually loaded.
Remember this when generating <xml3d> element from script.

**Comment by csvurt** [comment]
It's supposed to work if you add the ```<xml3d>``` element later too. I just extended the example code from your StackOverflow question and it seemed to work with the hotfix-4.9.4 build:

HTML Document:
```html
<html>
  <head>
     ... scripts ...
  </head>
  <body>
    <div id="content"></div>
  </body>
</html>
```
main.js:
```javascript
...
requirejs(['xml3d'], function (XML3D) { console.log(XML3D) });

setTimeout(function () {
    var xml = "<xml3d> ...xml3d scene... </xml3d>";
    var doc = $.parseXML(xml);
    $('#content').append(doc.childNodes[0]); //first child is the xml3d element
}, 1000)
```

Are you doing something different that causes the xml3d element to not be initialized after it's added?

**Comment by Arsakes** [comment]
Here is my code that doesn't work:

    requirejs(['lib1', 'lib2'..., 'xml3'], function (lib1, lib2.... XML3D) {
      var scene = new lib1();  // it generates <xml3d> </xml3d> and the content !
    }

Whereas this works:

    requirejs(['lib1', 'lib2'...], function (lib1, lib2....) {
      var scene = new lib1(); // it generates <xml3d> </xml3d> and the content !
      requirejs(['xml3d'], function (XML3D) {
        consol.elog('')
      }
    }

**Comment by csvurt** [comment]
Ok looks like there was another bug that slipped through because I was using $.parseXML, which causes the tagName field of generated elements to be lower case instead of the normal upper case in HTML. 

I pushed a fix to the hotfix-4.9.4 branch that should work for both cases. Could you build it again and let me know if that's fixed it for you?

**Comment by Arsakes** [comment]
It still doesn't work.
I think we didn't tackled the issue here.
NOTE: this is based on assumption that XML3D requires <xml3d> element to be present in the dom.
Now correct if I'm wrong, but I think my problem doesn't have anything to do with document.readyState value.
The problem in my case is I use script that at some points creates <xml3d> element - usually after the document is loaded. 
So it is perfectly possible for   `<xml3d>`     to not exist and for variable `document.readyState === "complete"`. In such case XML3D would init and don't work. 
I've did an experiment, I've put an additional line in XML3D library:

    console.log('STATE 0:', document.readyState)

And used my example (main loader for require.js)

    requirejs(['lib1', 'xml3d'...], function (lib1, xml3d....) {
      console.log('STATE 1:', document.readyState);
      var scene = new lib1(); // now we generate the <XML3D> element
    }

The result is:

    STATE 0: completed
    STATE 1: completed

and obviously XML3D doesn't work because there was no `xml3d` elem at the time of init.

My conclusion is: you cannot solve this problem by checking document state.
You must check if  'xml3d' exists or provide function for user to init xml3d by hand.

Of course I may be wrong.

**Comment by csvurt** [comment]
We also register a MutationObserver for inserted nodes the first time xml3d.js is loaded. This should detect any xml3d elements that are added to the DOM after the fact, even if they're "hidden" inside other elements that are appended (ie. a ```<div>``` with an ```<xml3d>``` element inside). If you search for the function ```resolveMutations``` in your xml3d.js you should see it.

The bug I fixed previously was actually inside this listener. It checked for elements that were added to the DOM with the tagName "xml3d" but didn't catch those with tagName "XML3D", that's why I thought it might have been what caused your problem.

Could you check if this works for you using the hotfix build?

```javascript
requirejs(['jquery-2.1.1', 'xml3d'], function() {
	var xml3dElement = $('<xml3d id="xml3dElem" width: 300px; height: 200px;"></xml3d>');
	$("body").append(xml3dElement);
});
```

You can change the libraries that are being loaded if you want. I've tried this here and it seems to initialize the XML3D element properly, if it also works for you at least we know the problem must be somewhere else. In that case it would be helpful to see your code that creates the xml3d element and adds it to the DOM, maybe it's doing something that we didn't anticipate.

**Comment by Arsakes** [comment]
It doesn't work (after correcting the simple error you made:
    <xml3d id="xml3dElem" width: 300px; height: 200px;"></xml3d>
shoudl be:
    <xml3d id="xml3dElem" style="width: 300px; height: 200px;"></xml3d>'

**Comment by csvurt** [comment]
FYI 3f0b1ba8b5b86e141c17f5f15f0792f31a0a77fa fixed another bug in the XML3D init handling, it may have been what was causing the problems here. This fix is now on master and the deployed scripts on xml3d.org.
